name: AmongUs
version: 1.0
author: [misleaded, _muaddib]
main: me.misleaded.amongUs.AmongUs
api-version: 1.16
commands:
  genMap:
    description: generates the map
    usage: /<command>
  join:
    description: joins queue
    usage: /<command>
  leave:
    description: leaves queue
    usage: /<command>
  create:
    description: creates new queue
    usage: /<command>   
  forcestart:
    description: forcestarts queue
    usage: /<command>
